train:
- $/dataset/char1/1/normal/b2/rgb/
- $/dataset/char1/1/normal/b3/rgb/
- $/dataset/char1/1/normal/b4/rgb/
- $/dataset/char1/1/soap/b2/rgb/
- $/dataset/char1/1/soap/b3/rgb/
- $/dataset/char1/1/soap/b4/rgb/
- $/dataset/char1/2/normal/b1/rgb/
- $/dataset/char1/2/normal/b3/rgb/
- $/dataset/char1/2/normal/b4/rgb/
- $/dataset/char1/2/soap/b1/rgb/
- $/dataset/char1/2/soap/b2/rgb/
- $/dataset/char1/2/soap/b3/rgb/
- $/dataset/char1/3/normal/b1/rgb/
- $/dataset/char1/3/normal/b2/rgb/
- $/dataset/char1/3/normal/b4/rgb/
- $/dataset/char1/3/soap/b1/rgb/
- $/dataset/char1/3/soap/b2/rgb/
- $/dataset/char1/3/soap/b4/rgb/
- $/dataset/char1/4/normal/b1/rgb/
- $/dataset/char1/4/normal/b2/rgb/
- $/dataset/char1/4/normal/b3/rgb/
- $/dataset/char1/4/soap/b1/rgb/
- $/dataset/char1/4/soap/b3/rgb/
- $/dataset/char1/4/soap/b4/rgb/
- $/dataset/char1/5/normal/b2/rgb/
- $/dataset/char1/5/normal/b3/rgb/
- $/dataset/char1/5/normal/b4/rgb/
- $/dataset/char1/5/soap/b2/rgb/
- $/dataset/char1/5/soap/b3/rgb/
- $/dataset/char1/5/soap/b4/rgb/
- $/dataset/char1/6/normal/b1/rgb/
- $/dataset/char1/6/normal/b3/rgb/
- $/dataset/char1/6/normal/b4/rgb/
- $/dataset/char1/6/soap/b1/rgb/
- $/dataset/char1/6/soap/b2/rgb/
- $/dataset/char1/6/soap/b3/rgb/
- $/dataset/char1/7/normal/b1/rgb/
- $/dataset/char1/7/normal/b2/rgb/
- $/dataset/char1/7/normal/b4/rgb/
- $/dataset/char1/7/soap/b1/rgb/
- $/dataset/char1/7/soap/b2/rgb/
- $/dataset/char1/7/soap/b4/rgb/
- $/dataset/char1/8/normal/b1/rgb/
- $/dataset/char1/8/normal/b2/rgb/
- $/dataset/char1/8/normal/b3/rgb/
- $/dataset/char1/8/soap/b1/rgb/
- $/dataset/char1/8/soap/b3/rgb/
- $/dataset/char1/8/soap/b4/rgb/
- $/dataset/char2/1/normal/b1/rgb/
- $/dataset/char2/1/normal/b3/rgb/
- $/dataset/char2/1/normal/b4/rgb/
- $/dataset/char2/1/soap/b1/rgb/
- $/dataset/char2/1/soap/b2/rgb/
- $/dataset/char2/1/soap/b4/rgb/
- $/dataset/char2/2/normal/b1/rgb/
- $/dataset/char2/2/normal/b2/rgb/
- $/dataset/char2/2/normal/b4/rgb/
- $/dataset/char2/2/soap/b1/rgb/
- $/dataset/char2/2/soap/b3/rgb/
- $/dataset/char2/2/soap/b4/rgb/
- $/dataset/char2/3/normal/b1/rgb/
- $/dataset/char2/3/normal/b2/rgb/
- $/dataset/char2/3/normal/b3/rgb/
- $/dataset/char2/3/soap/b2/rgb/
- $/dataset/char2/3/soap/b3/rgb/
- $/dataset/char2/3/soap/b4/rgb/
- $/dataset/char2/4/normal/b2/rgb/
- $/dataset/char2/4/normal/b3/rgb/
- $/dataset/char2/4/normal/b4/rgb/
- $/dataset/char2/4/soap/b1/rgb/
- $/dataset/char2/4/soap/b2/rgb/
- $/dataset/char2/4/soap/b3/rgb/
- $/dataset/char2/5/normal/b1/rgb/
- $/dataset/char2/5/normal/b3/rgb/
- $/dataset/char2/5/normal/b4/rgb/
- $/dataset/char2/5/soap/b1/rgb/
- $/dataset/char2/5/soap/b2/rgb/
- $/dataset/char2/5/soap/b4/rgb/
- $/dataset/char2/6/normal/b1/rgb/
- $/dataset/char2/6/normal/b2/rgb/
- $/dataset/char2/6/normal/b4/rgb/
- $/dataset/char2/6/soap/b1/rgb/
- $/dataset/char2/6/soap/b3/rgb/
- $/dataset/char2/6/soap/b4/rgb/
- $/dataset/char2/7/normal/b1/rgb/
- $/dataset/char2/7/normal/b2/rgb/
- $/dataset/char2/7/normal/b3/rgb/
- $/dataset/char2/7/soap/b2/rgb/
- $/dataset/char2/7/soap/b3/rgb/
- $/dataset/char2/7/soap/b4/rgb/
- $/dataset/char2/8/normal/b2/rgb/
- $/dataset/char2/8/normal/b3/rgb/
- $/dataset/char2/8/normal/b4/rgb/
- $/dataset/char2/8/soap/b1/rgb/
- $/dataset/char2/8/soap/b2/rgb/
- $/dataset/char2/8/soap/b3/rgb/
- $/dataset/char3/1/normal/b1/rgb/
- $/dataset/char3/1/normal/b2/rgb/
- $/dataset/char3/1/normal/b4/rgb/
- $/dataset/char3/1/soap/b1/rgb/
- $/dataset/char3/1/soap/b3/rgb/
- $/dataset/char3/1/soap/b4/rgb/
- $/dataset/char3/2/normal/b1/rgb/
- $/dataset/char3/2/normal/b2/rgb/
- $/dataset/char3/2/normal/b3/rgb/
- $/dataset/char3/2/soap/b2/rgb/
- $/dataset/char3/2/soap/b3/rgb/
- $/dataset/char3/2/soap/b4/rgb/
- $/dataset/char3/3/normal/b2/rgb/
- $/dataset/char3/3/normal/b3/rgb/
- $/dataset/char3/3/normal/b4/rgb/
- $/dataset/char3/3/soap/b1/rgb/
- $/dataset/char3/3/soap/b2/rgb/
- $/dataset/char3/3/soap/b3/rgb/
- $/dataset/char3/4/normal/b1/rgb/
- $/dataset/char3/4/normal/b3/rgb/
- $/dataset/char3/4/normal/b4/rgb/
- $/dataset/char3/4/soap/b1/rgb/
- $/dataset/char3/4/soap/b2/rgb/
- $/dataset/char3/4/soap/b4/rgb/
- $/dataset/char3/5/normal/b1/rgb/
- $/dataset/char3/5/normal/b2/rgb/
- $/dataset/char3/5/normal/b4/rgb/
- $/dataset/char3/5/soap/b1/rgb/
- $/dataset/char3/5/soap/b3/rgb/
- $/dataset/char3/5/soap/b4/rgb/
- $/dataset/char3/6/normal/b1/rgb/
- $/dataset/char3/6/normal/b2/rgb/
- $/dataset/char3/6/normal/b3/rgb/
- $/dataset/char3/6/soap/b2/rgb/
- $/dataset/char3/6/soap/b3/rgb/
- $/dataset/char3/6/soap/b4/rgb/
- $/dataset/char3/7/normal/b2/rgb/
- $/dataset/char3/7/normal/b3/rgb/
- $/dataset/char3/7/normal/b4/rgb/
- $/dataset/char3/7/soap/b1/rgb/
- $/dataset/char3/7/soap/b2/rgb/
- $/dataset/char3/7/soap/b3/rgb/
- $/dataset/char3/8/normal/b1/rgb/
- $/dataset/char3/8/normal/b3/rgb/
- $/dataset/char3/8/normal/b4/rgb/
- $/dataset/char3/8/soap/b1/rgb/
- $/dataset/char3/8/soap/b2/rgb/
- $/dataset/char3/8/soap/b4/rgb/
- $/dataset/char4/1/normal/b1/rgb/
- $/dataset/char4/1/normal/b2/rgb/
- $/dataset/char4/1/normal/b3/rgb/
- $/dataset/char4/1/soap/b2/rgb/
- $/dataset/char4/1/soap/b3/rgb/
- $/dataset/char4/1/soap/b4/rgb/
- $/dataset/char4/2/normal/b2/rgb/
- $/dataset/char4/2/normal/b3/rgb/
- $/dataset/char4/2/normal/b4/rgb/
- $/dataset/char4/2/soap/b1/rgb/
- $/dataset/char4/2/soap/b2/rgb/
- $/dataset/char4/2/soap/b3/rgb/
- $/dataset/char4/3/normal/b1/rgb/
- $/dataset/char4/3/normal/b3/rgb/
- $/dataset/char4/3/normal/b4/rgb/
- $/dataset/char4/3/soap/b1/rgb/
- $/dataset/char4/3/soap/b2/rgb/
- $/dataset/char4/3/soap/b4/rgb/
- $/dataset/char4/4/normal/b1/rgb/
- $/dataset/char4/4/normal/b2/rgb/
- $/dataset/char4/4/normal/b4/rgb/
- $/dataset/char4/4/soap/b1/rgb/
- $/dataset/char4/4/soap/b3/rgb/
- $/dataset/char4/4/soap/b4/rgb/
- $/dataset/char4/5/normal/b1/rgb/
- $/dataset/char4/5/normal/b2/rgb/
- $/dataset/char4/5/normal/b3/rgb/
- $/dataset/char4/5/soap/b2/rgb/
- $/dataset/char4/5/soap/b3/rgb/
- $/dataset/char4/5/soap/b4/rgb/
- $/dataset/char4/6/normal/b2/rgb/
- $/dataset/char4/6/normal/b3/rgb/
- $/dataset/char4/6/normal/b4/rgb/
- $/dataset/char4/6/soap/b1/rgb/
- $/dataset/char4/6/soap/b2/rgb/
- $/dataset/char4/6/soap/b3/rgb/
- $/dataset/char4/7/normal/b1/rgb/
- $/dataset/char4/7/normal/b3/rgb/
- $/dataset/char4/7/normal/b4/rgb/
- $/dataset/char4/7/soap/b1/rgb/
- $/dataset/char4/7/soap/b2/rgb/
- $/dataset/char4/7/soap/b4/rgb/
- $/dataset/char4/8/normal/b1/rgb/
- $/dataset/char4/8/normal/b2/rgb/
- $/dataset/char4/8/normal/b4/rgb/
- $/dataset/char4/8/soap/b1/rgb/
- $/dataset/char4/8/soap/b3/rgb/
- $/dataset/char4/8/soap/b4/rgb/

val:
- $/dataset/char1/1/normal/b1/rgb/
- $/dataset/char1/1/soap/b1/rgb/
- $/dataset/char1/2/normal/b2/rgb/
- $/dataset/char1/2/soap/b4/rgb/
- $/dataset/char1/3/normal/b3/rgb/
- $/dataset/char1/3/soap/b3/rgb/
- $/dataset/char1/4/normal/b4/rgb/
- $/dataset/char1/4/soap/b2/rgb/
- $/dataset/char1/5/normal/b1/rgb/
- $/dataset/char1/5/soap/b1/rgb/
- $/dataset/char1/6/normal/b2/rgb/
- $/dataset/char1/6/soap/b4/rgb/
- $/dataset/char1/7/normal/b3/rgb/
- $/dataset/char1/7/soap/b3/rgb/
- $/dataset/char1/8/normal/b4/rgb/
- $/dataset/char1/8/soap/b2/rgb/
- $/dataset/char2/1/normal/b2/rgb/
- $/dataset/char2/1/soap/b3/rgb/
- $/dataset/char2/2/normal/b3/rgb/
- $/dataset/char2/2/soap/b2/rgb/
- $/dataset/char2/3/normal/b4/rgb/
- $/dataset/char2/3/soap/b1/rgb/
- $/dataset/char2/4/normal/b1/rgb/
- $/dataset/char2/4/soap/b4/rgb/
- $/dataset/char2/5/normal/b2/rgb/
- $/dataset/char2/5/soap/b3/rgb/
- $/dataset/char2/6/normal/b3/rgb/
- $/dataset/char2/6/soap/b2/rgb/
- $/dataset/char2/7/normal/b4/rgb/
- $/dataset/char2/7/soap/b1/rgb/
- $/dataset/char2/8/normal/b1/rgb/
- $/dataset/char2/8/soap/b4/rgb/
- $/dataset/char3/1/normal/b3/rgb/
- $/dataset/char3/1/soap/b2/rgb/
- $/dataset/char3/2/normal/b4/rgb/
- $/dataset/char3/2/soap/b1/rgb/
- $/dataset/char3/3/normal/b1/rgb/
- $/dataset/char3/3/soap/b4/rgb/
- $/dataset/char3/4/normal/b2/rgb/
- $/dataset/char3/4/soap/b3/rgb/
- $/dataset/char3/5/normal/b3/rgb/
- $/dataset/char3/5/soap/b2/rgb/
- $/dataset/char3/6/normal/b4/rgb/
- $/dataset/char3/6/soap/b1/rgb/
- $/dataset/char3/7/normal/b1/rgb/
- $/dataset/char3/7/soap/b4/rgb/
- $/dataset/char3/8/normal/b2/rgb/
- $/dataset/char3/8/soap/b3/rgb/
- $/dataset/char4/1/normal/b4/rgb/
- $/dataset/char4/1/soap/b1/rgb/
- $/dataset/char4/2/normal/b1/rgb/
- $/dataset/char4/2/soap/b4/rgb/
- $/dataset/char4/3/normal/b2/rgb/
- $/dataset/char4/3/soap/b3/rgb/
- $/dataset/char4/4/normal/b3/rgb/
- $/dataset/char4/4/soap/b2/rgb/
- $/dataset/char4/5/normal/b4/rgb/
- $/dataset/char4/5/soap/b1/rgb/
- $/dataset/char4/6/normal/b1/rgb/
- $/dataset/char4/6/soap/b4/rgb/
- $/dataset/char4/7/normal/b2/rgb/
- $/dataset/char4/7/soap/b3/rgb/
- $/dataset/char4/8/normal/b3/rgb/
- $/dataset/char4/8/soap/b2/rgb/

nc: 8
names: ['0','1','2','3','4','5','6','7']